### ISSUE TITLE
Libboost-random 155

### ISSUE THREAD

**Issue by momo-the-monster** [wieden-kennedy/Cinder-WebSocketPP#3]
I created a new empty project with Tinderbox, including the master branch of Cinder-WebSocketPP. I get the following linker error:

```
Error   30  error LNK1104: cannot open file 'libboost_random-vc120-mt-sgd-1_55.lib'
```

I can't see this version included in the project properties, which link to:

```
Cinder-WebSocketPP\lib\msw\libboost_random-vc110-mt-sgd-1_53.lib
```

Is this version included somewhere else?
I'm using Windows 8.1, Cinder Release 0.8.6 and Visual Studio Express 2013

**Comment by icfixx** [comment]
Does the same problem persist for OSX as well ? 
I am getting 

(null): "boost::random::random_device::random_device()", referenced from:
(null): Websocketpp::random::random_device::int_generator<unsigned int, websocketpp::concurrency::basic>::int_generator() in WebSocketClient.o
